### PR TITLE
Fast Fall Mod

### PR DESCRIPTION
**Pull request by MrAnyone**
Makes the player falls very fast on midair.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
Anyone can check if this works on mineplex?

**Comment by camilleeyries** [comment]
coool !

**Comment by Janmm14** [comment]
How should it work on mineplex if its not ncp-compatible?

**Comment by mcccs** [comment]
Might work or might not work.

**Comment by Janmm14** [comment]
@mcccs ?

**Comment by ThisTestUser** [comment]
A lot of games don't use NCP. I'm not certain about how Mineplex Anti-Cheat works, like regen doesn't work, but if Alexander thinks glide works then fastfall should work.

**Comment by MrAnyone** [comment]
The fact is that since there are too many "non vanilla movements" on mineplex games, makes them unable to make a NCP that is to "sensitive" to that movements (like special fly moves or everything).
A normal NCP on mineplex would make things very unplayable, since their servers are lagged as %#@!.
So, it might work...

**Comment by ThisTestUser** [comment]
Then you should unblock it in AntiMAC.

**Comment by ThisTestUser** [comment]
You also need to disable glide if this mod is enabled, and maybe add a "see also" to glide.

**Comment by MrAnyone** [comment]
@ThisTestUser 
Disable *it* when glide is enabled, I think that glide is a priority.

**Comment by ThisTestUser** [comment]
But you also need to make fastfall disable glide, so if you enable fastfall last glide gets disabled.
I have already made glide disable fastfall if its enabled.

**Comment by camilleeyries** [comment]
UP

**Comment by jtrent238** [comment]
:+1:

**Comment by v0idst4r** [comment]
One of the wurst modules I've ever seen. Put a little more effort into your work.

**Comment by v0idst4r** [comment]
Really, who is ever going to use this? This will break jumping and also make you unable to swim up in water. You could've ar least checked the distance from the ground and if you were in water.

**Comment by MrAnyone** [comment]
Who will use the Tweark mod by the way??? hah.

I don't have the IDE anymore, and I don't have time to fix the branch conflicts.

Thanks for all the feedback from everyone.

**Pull request closed without merging**
